### ISSUE TITLE
The code for 'kgprompt.json'

### ISSUE THREAD

**Issue by XZhang00** [Hengrui-Gu/PokeMQA#4]
Hi, thanks for your solid work!
I want to test the performance on the MQUAKE dataset (more data), could you share the code for generating the corresponding 'kgprompt.json'? 

Looking forward to your reply!

**Comment by Hengrui-Gu** [comment]
Hi, thanks for your attention !

To generate the knowledge prompts, we employ an off-the-shelf entity linking model, [**ELQ**](https://arxiv.org/pdf/2010.02413), to identify the key entity (Wikidata-Qid) in each multi-hop question. Using the Qid, we retrieve the entity-related structured facts from the [Wikidata-dump](https://www.wikidata.org/wiki/Wikidata:Database_download) and construct the knowledge prompts for each question.

Since the ELQ model code is not lightweight and we haven't made any changes to it, we do not plan to integrate this code into our repository. You can follow the standard procedures outlined in the [ELQ repository](https://github.com/facebookresearch/BLINK/tree/main/elq) to recognize key entities and retrieve related facts from Wikidata. We will soon release a simple example code demonstrating how to construct knowledge prompts based on the retrieved structured facts of key entities. We hope this will be helpful to you !

**Comment by XZhang00** [comment]
Yeah, I got it. Thanks for your reply!
